version: "3.3"
services:
  protoc-all:
    image: namely/protoc-all:latest
    command: 
      -d api/proto
      -o api/generated
      -i third_party/googleapis
      -l go
      --with-gateway
    volumes:
      - ./:/defs